<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KRT-laptop" failures="1" tests="1" name="LoanTest" time="18.509" errors="0" timestamp="2025-09-08T17:36:17 IST">
  <testcase classname="com.banking.tests.LoanTest" name="applyForLoan" time="5.957">
    <failure type="java.lang.AssertionError" message="❌ Loan denial message not found! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Loan denial message not found! expected [true] but found [false]
at com.banking.tests.LoanTest.applyForLoan(LoanTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- applyForLoan -->
</testsuite> <!-- LoanTest -->
